import type { Dictionary } from './types';

export const en: Dictionary = {
  nav: { industries: 'Industries', howItWorks: 'How it works', benefits: 'What you get', pricing: 'Pricing', faq: 'FAQ', cta: 'Free consultation' },
  hero: {
    badge: 'We support specialists and freelancers',
    h1: 'Got a B2B offer? Start working without registering a company.',
    h1accent: 'B2B offer',
    bullets: [
      'Work with clients from around the world.',
      'Issue invoices officially in our system.',
      'Receive domestic and foreign currency payments.',
    ],
    cta: 'Free consultation',
    tagline: 'Thanks to cooperation with Fundacja Firma Dla Każdego, you can provide services for clients without registering your own company.',
    modules: ['Invoicing', 'Banking', 'B2B Contracts', 'Accounting', 'Taxes', 'HR', 'Legal', 'Benefits'],
  },
  stats: [
    { value: '10+', label: 'years on the market' },
    { value: '8,000+', label: 'clients worldwide' },
    { value: '50,000+', label: 'invoices issued' },
    { value: '30%', label: 'average cost savings' },
  ],
  industries: {
    heading: 'Industries we work with',
    list: [
      'IT / Developers', 'Graphic Designers & Illustrators', 'Designer / Architect',
      'Photographers / Videographers', 'Content Creators / UGC', 'Musicians & Audio Creators',
      'Translators', 'Foreign Language Teachers', 'Article & Book Authors',
      'E-commerce', 'Journalists / Copywriters', 'Coaching & Personal Development',
    ],
    exclusionsHeading: 'Who we do NOT work with',
    exclusions: [
      { title: 'License or concession required', body: 'If your service requires a concession, license, or entry in an industry register.' },
      { title: 'Excluded industries', body: 'Construction, mechanics, cosmetic services, catering, taxi, deliveries, imports from China, logistics, transportation.' },
      { title: 'When we advise against it', body: 'You have a well-optimized business with a good accountant. You employ people full-time. You are building a company for sale to an investor. In these cases, we will say honestly that the incubator does not make sense.' },
    ],
  },
  threeOptions: {
    heading: 'You got a B2B contract. You have three options.',
    options: [
      { label: 'Your own business', text: 'Quick, but you take on contributions, declarations and accounting permanently. A decision that is hard to reverse mid-contract.' },
      { label: 'Civil contract', text: 'The client usually does not want this, because it means costs and contribution obligations on their side.' },
      { label: 'Incubator', text: 'You invoice immediately without registering a company. If after a few months you decide you prefer your own business, you switch without obstacles.' },
    ],
  },
  howItWorks: {
    heading: 'How to start cooperation?',
    processLabel: 'Process',
    steps: [
      { num: '01', title: 'Initial consultation', body: 'We discuss the scope of services, cooperation model, working mode and settlement terms. We verify your residence status and documents. If needed, we help you obtain the necessary documents.' },
      { num: '02', title: 'Signing the cooperation agreement', body: 'You sign the cooperation agreement with the Foundation online or at our office in Warsaw.' },
      { num: '03', title: 'Verification of the B2B contract with your client', body: 'We also verify the B2B contract with your client. The Foundation is the formal contracting party. The agreement can be concluded between the client and the Foundation, or between the client, the Foundation and you — depending on the agreed cooperation model.' },
      { num: '04', title: 'You start work and issue invoices', body: 'You receive access to the financial system, bank account, and necessary instructions. You officially issue invoices to companies and individuals in Poland and abroad. You receive remuneration in accordance with the agreed terms of cooperation.' },
    ],
    cta: 'Free consultation',
  },
  benefits: {
    heading: 'What do you get in our support program?',
    programLabel: 'Support program',
    cta: 'I want to cooperate',
    categories: [
      { label: 'CLIENTS FROM AROUND THE WORLD', title: 'You work globally', items: ['Cooperation with clients from around the world', 'Billing companies and individuals', 'B2B contract handling and verification', 'Support in 4 languages: PL / EN / UA / RU'] },
      { label: 'PAYMENTS', title: 'Wide payment options from clients', items: ['3 business sub-accounts', 'Payments in PLN, USD, EUR and 50+ currencies', 'Account with IBAN / SWIFT / PayPal, Payoneer payments', 'Possibility of receiving payments in USDT'] },
      { label: 'LAW, TAXES & SUPPORT', title: 'Accounting, HR, administrative and legalization support', items: ['Dedicated HR supervisor', 'Legal and tax advisory', 'PIT and ZUS tax settlement handling', 'Certificates and Tax declarations'] },
      { label: 'BENEFITS', title: 'Sports and medical packages', items: ['Option to join NFZ health insurance', 'Medicover medical packages', 'MultiSport sports packages', "Young Person's Relief and student solutions — in accordance with applicable law"] },
    ],
  },
  pricing: {
    heading: 'Pricing',
    sub: 'Simple, transparent monthly fee — no hidden charges.',
    popular: 'Most popular',
    standardLabel: 'Standard Package',
    thresholdLabel: 'Payout threshold',
    tiers: [
      { threshold: 'Up to 10,000 PLN / month', price: '400 PLN', period: '/ month', desc: 'Standard package.', highlight: false },
      { threshold: '10,000 – 30,000 PLN / month', price: '700 PLN', period: '/ month', desc: 'For regularly cooperating specialists.', highlight: true },
      { threshold: 'Over 30,000 PLN / month', price: '1,050 PLN', period: '/ month', desc: 'For advanced B2B contracts and large-scale work.', highlight: false },
    ],
    cta: 'Schedule a consultation',
  },
  comparison: {
    heading: 'Less paperwork, more profit',
    lossLabel: 'You no longer need to',
    gainLabel: 'You gain',
    losses: [
      'Rent a virtual office.',
      'Pay for a separate accounting service.',
      'Register your own company (sole trader).',
      'Register for PIT/ZUS yourself or handle your own taxes.',
    ],
    gains: [
      'You officially cooperate with clients from around the world.',
      'You settle taxes in full compliance with applicable regulations.',
      'You have documented income — transparently and without unnecessary complications.',
      'You receive documentary basis for residence legalization purposes.',
    ],
  },
  faq: {
    heading: 'Frequently Asked Questions',
    items: [
      { q: 'What do I need to do to start working with the Foundation?', a: 'Contact the Foundation via the application form, by phone or email. The first step is to review the informational materials and the cooperation agreement. After accepting the terms, the agreement is signed.' },
      { q: 'Who signs the B2B contract with my client?', a: 'The B2B contract with your client is signed by the Foundation. The Foundation is the contracting party — with its own NIP, REGON and address.\n\nYou perform the services specified in the contract as the Service Provider, while the Foundation handles the formal, administrative and legal aspects of the contract.' },
      { q: 'How quickly can I start working?', a: 'The entire process — from consultation, through signing the agreement, to being able to issue the first invoice — can take as little as 1 business day.\n\nThe start time depends on your situation, arrangements with your client, completeness of documents and efficiency of communication.\n\nAfter signing the agreement and confirming all terms, you will receive the necessary instructions and will be able to start providing services and issuing invoices.' },
      { q: 'What does using the Foundation\'s legal personality look like in practice?', a: 'The Foundation\'s registration details appear as the seller on invoices. Contracts with clients are signed by the Foundation after prior analysis by lawyers.' },
      { q: 'Who will I be in contact with? Will I have a dedicated account manager?', a: 'We provide support in several areas: administration, HR and personnel, accounting, and residence legalization.\n\nYou will also receive a dedicated HR specialist you can contact in your preferred language: PL / EN / UA / RU.\n\nWe are available Monday to Friday, 9:00 AM – 5:00 PM. We also have an office in Warsaw — by prior appointment you can meet us in person.' },
      { q: 'Do you provide documents needed for residence legalization in Poland?', a: 'Yes. Based on your cooperation with the Foundation, you can apply for residence legalization in Poland if you meet the required conditions.\n\nResidence legalization consultations are included in the package. Document preparation, application submission and obtaining a work permit are additionally paid legalization services.\n\nFor example, preparing the document set for a temporary residence card (TRC) application with Appendix No. 1 costs 400 PLN.' },
      { q: 'On what basis do I receive my remuneration?', a: 'Remuneration is paid based on an appropriate civil law contract, e.g. a mandate contract or a specific-task contract.\n\nThe type of contract and the method of taxation are determined based on the scope of services provided and the documents submitted during the consultation. Student reliefs are applied in accordance with applicable regulations, after confirming current student status.' },
      { q: 'For what period is the cooperation agreement concluded?', a: 'The cooperation agreement is concluded for an indefinite period.\n\nThis means you can end the cooperation whenever you decide to. A one-month notice period applies in accordance with the regulations.' },
      { q: 'How and when is the service fee charged?', a: 'The service fee is charged by the 4th of each month.\n\nSettlement periods correspond to calendar months — from the first to the last day of the month. The fee is charged from your business sub-account. If the sub-account has insufficient funds, you can make a payment via external bank transfer.\n\nFor external bank transfers, 23% VAT must be added to the fee.' },
      { q: 'What taxes are paid during cooperation?', a: 'The method of settlement depends on the type of contract concluded and individual cooperation terms.\n\nTypically, PIT income tax and ZUS social security contributions may apply, depending on the type of contract and your situation. Settlement details are determined during the consultation.' },
      { q: 'Can I invoice foreign clients?', a: 'Yes. Invoices in EUR, USD and other currencies, account with IBAN/SWIFT, two foreign currency accounts at no extra charge, PayPal and USDT payments.' },
      { q: 'Does the incubator support the Young Person\'s Relief and students?', a: 'Yes. People under 26 benefit from the young person\'s relief, and students do not pay ZUS contributions — in accordance with applicable law. We take this into account in the settlement.' },
      { q: 'Is this legal?', a: 'Yes. A business incubator is a solution that has been operating in Poland for years: the Foundation is the contracting party and taxpayer, and you provide services as a person cooperating with the Foundation. Invoices are issued by the Foundation, and tax settlements are on their side. Upon request, we will explain the legal basis to your client.' },
      { q: 'What if I have no contracts one month?', a: 'You do not pay tax on revenue that did not exist. The monthly fee according to your package is charged from your sub-account by the 4th of the month. If the sub-account has insufficient funds, you can pay via external bank transfer (with 23% VAT added). The question of the fee for a month without invoices is discussed individually before signing the agreement — you will know before you decide.' },
      { q: 'Can I switch to my own business later?', a: 'Yes, at any time. There is no minimum period. Many people start in the incubator, check if the contract is stable, and only then register a company. We help with the transition.' },
    ],
  },
  contact: {
    heading: 'Schedule a consultation',
    sub: 'Fill in the form — we reply within 1 business day.',
    fields: { name: 'First name', email: 'E-mail', phone: 'Phone (optional)', description: 'Describe your situation', descriptionPlaceholder: 'e.g. what contract you got, when it starts, for which client...' },
    submit: 'Send',
    submitNote: 'We reply within 1 business day. No obligations.',
    consentRodo: 'I consent to the processing of my personal data in order to respond to my inquiry. I have read the',
    consentMarketing: 'I want to receive information about the Foundation\'s services by email or phone. I can withdraw my consent at any time.',
    privacyLink: 'Privacy Policy',
    success: 'Thank you! We\'ll reply within 1 business day.',
    validation: { nameMin: 'Name must have at least 2 characters', emailRequired: 'Provide your e-mail address', emailInvalid: 'Provide a valid e-mail address', emailDisposable: 'Provide a permanent e-mail address, not a disposable one', descMin: 'Describe your situation (min. 10 characters)', descMax: 'Maximum 1000 characters', consentRequired: 'Consent to data processing is required' },
  },
  footer: { rights: '© 2026 Fundacja Firma dla każdego. All rights reserved.', officeLabel: 'Office', workdays: 'Mon – Fri', privacy: 'Privacy Policy' },
  heroBadges: [
    { main: 'Up to 50 invoices / month', sub: 'included in the plan' },
    { main: 'International payments', sub: '50+ currencies' },
  ],
};
